# Base image from Jetson PyTorch wheels
FROM $(autotag l4t-pytorch)

# Set working directory
WORKDIR /workspace/doorbell_compliment_service

# Copy only your application code
COPY app/ ./app/
COPY requirements.txt .

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Expose port
EXPOSE 8080

# Run the FastAPI app with Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
